/controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    chain_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
 
/chain_joint_trajectory_controller:
  ros__parameters:
    joints:
      - agent_n2_pivot_base_joint
      - agent_n3_pivot_base_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: true
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      agent_n2_female_base_joint:
        trajectory: 0.05
        goal: 0.0
      agent_n3_female_base_joint:
        trajectory: 0.05
        goal: 0.0
