/namespace_tag/controller_manager:
  ros__parameters:
    update_rate: 50

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/namespace_tag/position_controller:
  ros__parameters:
    joints:
      - base_female_joint